- classes/column.php
- classes/column/custom-field.php
- readme.txt
Link type added for Custom Field
> #41 cf link type

- classes/storage_model.php
- classes/storage_model/comment.php
- classes/storage_model/post.php
- classes/storage_model/user.php
- readme.txt
https://github.com/codepress/admin-columns-issues/issues/352
> #352 subpages

- classes/storage_model.php
- readme.txt
https://github.com/codepress/admin-columns-issues/issues/351
> #351 storage model init manage columns fix

- classes/column.php
- classes/settings.php
- classes/storage_model.php
- classes/third_party/yoast_seo.php
https://github.com/codepress/admin-columns-issues/issues/366
> 366-3rd-party-fix

- classes/settings.php
- classes/utility.php
https://github.com/codepress/admin-columns-issues/issues/438
> #438 settings message

- codepress-admin-columns.php
fixes https://github.com/codepress/admin-columns-issues/issues/475
> get primary column based on the acp column set

- codepress-admin-columns.php
- readme.txt
fixes https://github.com/codepress/admin-columns-issues/issues/487
> row actions fix

- classes/column.php
- classes/column/actions.php
- classes/column/comment/excerpt.php
- classes/column/custom-field.php
- classes/column/link/notes.php
- classes/column/media/full-path.php
- classes/column/post/before-moretag.php
- classes/column/post/comment-count.php
- classes/column/post/content.php
- classes/column/post/estimated-reading-time.php
- classes/column/post/excerpt.php
- classes/column/post/permalink.php
- classes/column/used-by-menu.php
- classes/column/user/description.php
- classes/column/user/post-count.php
- classes/column/user/registered.php
fixes https://github.com/codepress/admin-columns-issues/issues/458
> changed get_value_by_meta()

- classes/settings.php
- classes/storage_model.php
- codepress-admin-columns.php
fixes https://github.com/codepress/admin-columns-issues/issues/501
> 501-hotfix

- codepress-admin-columns.php
fixes https://github.com/codepress/admin-columns-issues/issues/511
> show_ui instead of public for get_taxonomies

- assets/js/admin-columns.js
- classes/column.php
- classes/column/default.php
- classes/storage_model.php
- classes/storage_model/comment.php
- classes/storage_model/link.php
- classes/storage_model/media.php
- classes/storage_model/post.php
- classes/storage_model/user.php
- classes/utility.php
https://github.com/codepress/admin-columns-issues/issues/508
> #508 refactor sorting

- assets/js/admin-settings.js
- classes/column.php
- classes/column/wp-default.php
- classes/column/wp-plugin.php
- classes/settings.php
- classes/storage_model.php
https://github.com/codepress/admin-columns-issues/issues/530
> #530 refactor storage model

- classes/column.php
- classes/helper/array.php
- classes/storage_model.php
https://github.com/codepress/admin-columns-issues/issues/552
> #552 make post order column use pro interfaces

- classes/Column.php
- classes/ListingsScreen.php
- classes/Settings.php
- classes/Settings/Tab/Columns.php
- classes/StorageModel.php
- classes/StorageModel/Comment.php
- classes/StorageModel/Media.php
- classes/StorageModel/Post.php
- classes/StorageModel/PostAbstract.php
- classes/StorageModel/User.php
- classes/ThirdParty/WPML.php
- codepress-admin-columns.php
https://github.com/codepress/admin-columns-issues/issues/544
> #544 refactor storage model

- classes/Column/Media/LastModifiedAuthor.php
- classes/Column/Media/Modified.php
- readme.txt
Fixes and closes https://github.com/codepress/admin-columns-issues/issues/639
> Made Last Modified Author and Date available for Media

- classes/Settings/Column/CustomFieldType.php
- readme.txt
https://github.com/codepress/admin-columns-issues/issues/862
> 862 custom field image urls

- classes/Column/UsedByMenu.php
- classes/ListScreen.php
- classes/ListScreen/Post.php
- classes/Settings/Column/LinkToMenu.php
https://github.com/codepress/admin-columns-issues/issues/866
> 866 editable menus

- classes/Column/Post/Roles.php
fixes https://github.com/codepress/admin-columns-issues/issues/892
> Roles column back to working version

- classes/Column/User/ShowToolbar.php
fixes https://github.com/codepress/admin-columns-issues/issues/941
> raw_value now uses boolean instead of string

- classes/Column/Comment/WordCount.php
fixes https://github.com/codepress/admin-columns-issues/issues/940
https://github.com/engelen/cac-addon-export/issues/10
> raw_value uses correct param

- classes/Column/Post/Content.php
- classes/Column/Post/Excerpt.php
- classes/Column/User/Description.php
https://github.com/codepress/admin-columns-issues/issues/783
> Before After Fields added

- classes/Settings/Column/Date.php
- classes/Settings/Column/DateTimeFormat.php
- classes/Settings/Column/Time.php
- templates/settings/setting-date.php
close https://github.com/codepress/admin-columns-issues/issues/1004
> 1004 acf time field show display format instead of return format

- classes/Admin/Page/Columns.php
- classes/Notice/Review.php
- classes/Preferences.php
- classes/Preferences/Site.php
- classes/Preferences/User.php
https://github.com/codepress/admin-columns-pro/pull/220
> 1037 create acpreferences for site and user

- classes/Column/Post/AuthorName.php
https://github.com/codepress/admin-columns-issues/issues/1068
> Author Name Column fix

- classes/Admin/Page/Columns.php
- classes/Admin/Promo.php
- classes/Column/User/LastName.php
- classes/Settings/Column/AttachmentDisplay.php
- classes/Settings/Column/PathScope.php
- codepress-admin-columns.php
Related to https://github.com/codepress/admin-columns-issues/issues/1070
Corrections
- Added missing Gettext function
- Added missing textdomain
- Corrected strings to merge with existent similar strings
> [I18n] Strings corrections

- classes/Admin/Help/CustomField.php
- classes/Admin/Page/Columns.php
- classes/Admin/Page/Help.php
- classes/Column/Comment/AuthorUrl.php
- classes/Settings/Column/CustomFieldType.php
- classes/Settings/Column/LinkLabel.php
- classes/Settings/Column/PathScope.php
- Solves issue https://github.com/codepress/admin-columns-issues/issues/1074
- Correct typos
> [i18n] Custom Field Types names consistency

- classes/Autoloader.php
- readme.txt
https://github.com/codepress/admin-columns-issues/issues/1119
> Check for system files to prevent fatal errors

- assets/css/admin-general.css
- assets/css/admin-page-columns.css
- assets/css/table.css
- assets/js/admin-page-columns.js
- assets/js/admin-page-settings.js
- assets/js/table.js
- src/js/admin/columns/events/label.ts
- src/js/admin/columns/settings/label.ts
- src/scss/admin-page-columns.scss
- templates/settings/setting-label-icons.php
fixed https://github.com/codepress/admin-columns-pro/issues/523
> Wip icon search

- classes/ApplyFilter/ValidAudioMimetypes.php
- classes/ApplyFilter/ValidVideoMimetypes.php
- classes/Column/Media/Preview.php
- classes/Column/Media/VideoPlayer.php
- classes/View/Embed/Video.php
- readme.txt
- templates/embed/video.php
Fixes
https://github.com/codepress/admin-columns-pro/issues/593
> Preview Audio and Video
